// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu3AhbSpBnlZZKGfjOCqWDOdWHJlMLfVk',
    appId: '1:817639708689:web:98a24bb2bacd0d210e39b0',
    messagingSenderId: '817639708689',
    projectId: 'e-commerce-app-faacc',
    authDomain: 'e-commerce-app-faacc.firebaseapp.com',
    storageBucket: 'e-commerce-app-faacc.appspot.com',
    measurementId: 'G-JE18ZMR1J1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz5F0N8WVS_St6cGW9uK04WJO0yl9Z5Cc',
    appId: '1:817639708689:android:5ca206b68a6ef9760e39b0',
    messagingSenderId: '817639708689',
    projectId: 'e-commerce-app-faacc',
    storageBucket: 'e-commerce-app-faacc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWEsS0A_k-ROANYURkKwlCyVan7D561XA',
    appId: '1:817639708689:ios:84d6fd306520076c0e39b0',
    messagingSenderId: '817639708689',
    projectId: 'e-commerce-app-faacc',
    storageBucket: 'e-commerce-app-faacc.appspot.com',
    iosBundleId: 'com.appdeveloper.eCommerce',
  );
}
